<a href="https://colab.research.google.com/github/dsaha21/TF_Notebooks/blob/main/00_tensrflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(f"The value of 12 + 13 is -->{(12+13)}")

The value of 12 + 13 is -->25


Lets start below : 


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
#Check no. tensor dimension
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vec=tf.constant([10,10,10])
vec

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
vec.ndim

1

In [ ]:
mat=tf.constant([[10.,7.],[7.,10.],[4.,9.]],dtype=tf.float16)
mat

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 4.,  9.]], dtype=float16)>

In [ ]:
print(mat.ndim)

2


In [ ]:
#So scalar-->1 dim
# vec --> 2 dim
# scalar --> ? dim 

tensor=tf.constant([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[11,22,33],[44,55,66]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]],

       [[11, 22, 33],
        [44, 55, 66]]], dtype=int32)>

In [ ]:
change_tensor=tf.Variable([10,7])
unchange_tensor=tf.constant([10,7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
change_tensor[0].assign(7)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#for unchangeable tensor
#unchange_tensor[0].assign(7)

AttributeError: ignored

###**Random** **tensors** 

In [ ]:
#Why random tensors? 
#--> First initialisation

#Create random tf
r1=tf.random.Generator.from_seed(42) #setting seed
r1=r1.normal(shape=(3,2))
r2=tf.random.Generator.from_seed(42) #setting seed
r2=r2.normal(shape=(3,2))

r1,r2,r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
not_shuff=tf.constant([[1,2],[3,4],[5,6]])
#not_shuff
tf.random.shuffle(not_shuff,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuff,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

###**Numpy** **Array** --> 20/5/22

In [ ]:
#tf.ones([10,7])
tf.zeros([3,4])
# print("============")
# tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as n 
nA = n.arange(1,25,dtype=n.int32)
nA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#A=tf.constant(nA)
#A
A=tf.constant(nA,shape=(2,2,3,2))
B=tf.constant(nA)
A.ndim

4

###Getting Info From Tensors --> 21/5/22

In [ ]:
#Shape, Rank, Axis, Size
r4t=tf.zeros(shape=(2,3,4,5))

In [ ]:
#r4t
r4t.ndim,r4t.shape, tf.size(r4t)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print(f"Datatype... = {r4t.dtype}" )
print("Datatype... = ",r4t.dtype )

Datatype... = <dtype: 'float32'>
Datatype... =  <dtype: 'float32'>


In [ ]:
# somelist=[1,23,4,7]
# print(somelist[:2])
r4t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
r4t[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#changing extra dimension 
import numpy as n
r2t=tf.constant([[10,7],[1,3]],dtype=n.int16)
r2t

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[10,  7],
       [ 1,  3]], dtype=int16)>

In [ ]:
r2t.shape, r2t.ndim
r2t[-1]

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 3], dtype=int16)>

In [ ]:
#Add in extra dimen to our rank 2 tensor
r3t=r2t[..., tf.newaxis]
r3t
#alternative --> tf.expand_dims(r2t,axis=-1) -->expanding final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int16, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 3]]], dtype=int16)>

In [ ]:
tf.expand_dims(r2t,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int16, numpy=
array([[[10,  7],
        [ 1,  3]]], dtype=int16)>

### Maniputlating Tensors 

In [ ]:
#Basic Operations 
ten=tf.constant([[10,7],[3,4]])
ten + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
ten

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
ten=ten-10
#Like this sub, Mul, div and arithmetic operations 

In [ ]:
#functions 
tf.multiply(ten ,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Matrix Multiplication -->22/5/22
tf.matmul(ten,ten)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
ten*ten

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#ten @ ten
x=tf.constant([[1,2],
                   [3,4],
                   [5,6]])
y=tf.constant([[7,8],
                   [9,10],
                   [11,12]])
tf.reshape(ten32_2,shape=(2,3))
#tf.matmul(,ten32_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
ten32_1 @ tf.reshape(ten32_2,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(ten32_1, shape=(2,3)),ten32_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
#above outputs are diff 
#transpose
x,tf.transpose(x),tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
#Matmul with transpose
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

###THE DOT PRODUCT

In [ ]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
print("Normal y :")
print(y,"\n")
print("Y reshaped... to 2,3 : ")
print(tf.reshape(y,shape=(2,3)),"\n")

print("The y transpose is ...")
print(tf.transpose(y))

Normal y :
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped... to 2,3 : 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

The y transpose is ...
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
x=tf.constant([[1,2],
                   [3,4],
                   [5,6]])
y=tf.constant([[7,8],
                   [9,10],
                   [11,12]])
tf.matmul(x,tf.transpose(y)), tf.transpose(y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [ ]:
y2=tf.constant([[ 8,  10, 12],
        [ 7, 9, 11]])
tf.matmul(x,y2), print(x,"===========",y2)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) =========== tf.Tensor(
[[ 8 10 12]
 [ 7  9 11]], shape=(2, 3), dtype=int32)


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 22,  28,  34],
        [ 52,  66,  80],
        [ 82, 104, 126]], dtype=int32)>, None)

In [ ]:
#tf.cast

### AggreGating Tensor 

In [ ]:
#Get absolute values 
D=tf.constant([-7,10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# from tensorflow.python.ops.gen_array_ops import size
# #get min, max, mean of a tensor , sum of a tensor 
# import numpy as n
# rt=tf.constant(n.random.randint(0,100,size=50))
# rt

In [ ]:
tf.size(rt), rt.shape, rt.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
print(tf.reduce_min(rt))
print(tf.reduce_sum(rt))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2526, shape=(), dtype=int64)


In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(rt)

<tf.Tensor: shape=(), dtype=int64, numpy=851>

In [ ]:
tfp.stats.stddev(tf.cast(rt , dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.167953>

In [ ]:
#pos max and min
tf.random.set_seed(42)
rt2=tf.random.uniform(shape=[50])
rt2

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(rt2)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
rt2[tf.argmax(rt2)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
rt2[tf.argmax(rt2)]==tf.reduce_max(rt2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Squeezing a tensor 
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
print(G.shape)
print(tf.squeeze(G))

(1, 1, 1, 1, 50)
tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)


In [ ]:
#One hot encodings
sl=[0,1,2,3]
tf.one_hot(sl,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Squaring and logs 
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
import numpy as n
tf.sqrt(tf.cast(H,dtype=n.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

### Tensors and Numpy

In [ ]:
#create a tensor directly from numpy 
J=tf.constant(tf.cast(n.array([2.,6.,10.]),dtype=tf.float32))
J

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.,  6., 10.], dtype=float32)>

In [ ]:
n.array(J),type(n.array(J))

(array([ 2.,  6., 10.], dtype=float32), numpy.ndarray)

In [ ]:
type(J.numpy())

numpy.ndarray

In [ ]:
#Finding GPU access
import tensorflow as tf
tf.test.is_gpu_available

<function tensorflow.python.framework.test_util.is_gpu_available>

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon May 23 18:10:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#CUDA is the interface between code tensorflow and server 


## PRACTICE QUESTIONS 

In [ ]:
import tensorflow as tf
print(f"The scalar is --> {tf.constant(7)}")
print(f"The vector is -->{tf.constant([10,7])}")
print(f"The matrix is -->{tf.constant([[10,7],[7,10]])}")

The scalar is --> 7
The vector is -->[10  7]
The matrix is -->[[10  7]
 [ 7 10]]


In [ ]:
s=tf.constant(7)
v=tf.constant([10,7])
m=tf.constant([[10,7],[7,10]])
tf.shape(s), tf.rank(s), tf.size(s)

(<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
#import numpy as n
ten1=tf.random.uniform(shape=(5,300))
ten1
ten2=tf.random.uniform(shape=(5,300))

In [ ]:
ten1x2 = ten1 @ tf.transpose(ten2) 
ten1x2
#Also ten1x2=tf.matmul(ten1, tf.transpose())

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.95199 , 82.11325 , 73.95156 , 74.79049 , 74.587326],
       [71.51189 , 76.42964 , 67.84483 , 69.590744, 71.47393 ],
       [75.86295 , 81.40393 , 70.31673 , 72.560905, 74.71447 ],
       [75.02542 , 78.53784 , 69.99597 , 69.07254 , 72.829666],
       [78.7571  , 81.197296, 72.62836 , 71.307625, 73.110466]],
      dtype=float32)>

In [ ]:
import tensorflow_probability as tfp
ten12dot=tf.tensordot(tf.transpose(ten1),ten2,axes=1)
ten12dot

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.94991285, 1.6380614 , 0.7567318 , ..., 1.064566  , 1.1853737 ,
        1.1344318 ],
       [1.270238  , 1.6421738 , 0.946968  , ..., 1.7710956 , 1.6824267 ,
        1.5979708 ],
       [1.1901338 , 1.8228705 , 0.9690808 , ..., 1.301645  , 1.3418463 ,
        1.582002  ],
       ...,
       [1.3781058 , 2.0923822 , 1.074112  , ..., 1.1462023 , 1.3693014 ,
        1.6192343 ],
       [1.1299608 , 1.5188264 , 0.75485516, ..., 1.4783139 , 1.366429  ,
        1.5069255 ],
       [0.9517712 , 1.2318205 , 0.8588178 , ..., 1.3497803 , 1.4436392 ,
        0.95209265]], dtype=float32)>

In [ ]:
ten6=tf.random.uniform(shape=(224,224,3),minval=0,maxval=1)
ten6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.00757432, 0.03898835, 0.84129107],
        [0.71079576, 0.2973081 , 0.02728081],
        [0.17114365, 0.5061023 , 0.8026166 ],
        ...,
        [0.29506457, 0.38910902, 0.50599897],
        [0.10109484, 0.02711725, 0.029284  ],
        [0.06140196, 0.07545626, 0.9020214 ]],

       [[0.02471066, 0.9146466 , 0.08117902],
        [0.75015485, 0.7955394 , 0.7690494 ],
        [0.9069294 , 0.30945432, 0.54707587],
        ...,
        [0.80050564, 0.35932755, 0.33695114],
        [0.08285773, 0.742864  , 0.06846833],
        [0.16797459, 0.29275596, 0.28468895]],

       [[0.54471886, 0.39191496, 0.21666443],
        [0.70743   , 0.44767737, 0.90934825],
        [0.5175557 , 0.61201787, 0.01424479],
        ...,
        [0.6418102 , 0.756091  , 0.31798828],
        [0.5613377 , 0.18644857, 0.3481238 ],
        [0.47293317, 0.74486685, 0.7975135 ]],

       ...,

       [[0.25313497, 0.18045592, 0.11241508],
        [0.14

In [ ]:
tf.reduce_min(ten6)

<tf.Tensor: shape=(), dtype=float32, numpy=2.503395e-06>

In [ ]:
tf.reduce_max(ten6)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999666>

In [ ]:
ten8=tf.random.uniform(shape=(1,224,224,3))

In [ ]:
ten9=tf.squeeze(ten8)
ten9

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.91267335, 0.06405628, 0.6914836 ],
        [0.25482905, 0.8028041 , 0.6411874 ],
        [0.40771306, 0.82360697, 0.7687917 ],
        ...,
        [0.402861  , 0.43657959, 0.19284427],
        [0.41895044, 0.24705684, 0.21858335],
        [0.57417667, 0.0039345 , 0.86314857]],

       [[0.20677161, 0.8968768 , 0.01781416],
        [0.34694326, 0.33241236, 0.8343221 ],
        [0.95851755, 0.9365635 , 0.2758509 ],
        ...,
        [0.58148396, 0.5353887 , 0.6328701 ],
        [0.7864964 , 0.8252971 , 0.36028266],
        [0.67264307, 0.81794703, 0.29568124]],

       [[0.3267033 , 0.44865155, 0.90847266],
        [0.89656687, 0.6636957 , 0.2243743 ],
        [0.11902058, 0.39717567, 0.5926701 ],
        ...,
        [0.9707291 , 0.94070673, 0.36112893],
        [0.16518676, 0.53944814, 0.10094142],
        [0.78863835, 0.40960264, 0.1890173 ]],

       ...,

       [[0.04324865, 0.28476107, 0.54180586],
        [0.92

In [ ]:
ten10=tf.constant([3,1,2,99,100,8,3,0,6,50],shape=[10])
tf.argmax(ten10)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
tf.one_hot(ten10,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>